// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ConsoleEF.Models;

public partial class Mylog
{
    public Guid Id { get; set; }

    public string? ProcessId { get; set; }

    public string? TxtData { get; set; }

    public byte[]? BinData { get; set; }

    public DateTime Crt { get; set; }

    public DateTime Upd { get; set; }
}