// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ConsoleEF.Models;

public partial class SampleDbContext : DbContext
{
    public SampleDbContext(DbContextOptions<SampleDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Mylog> Mylogs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Mylog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__mylog__3213E83FBE931EBC");

            entity.ToTable("mylog");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.BinData).HasColumnName("bin_data");
            entity.Property(e => e.Crt)
                .HasColumnType("datetime")
                .HasColumnName("crt");
            entity.Property(e => e.ProcessId)
                .HasMaxLength(128)
                .HasColumnName("process_id");
            entity.Property(e => e.TxtData).HasColumnName("txt_data");
            entity.Property(e => e.Upd)
                .HasColumnType("datetime")
                .HasColumnName("upd");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}